import { FormField } from '../types'

export const fields: FormField[] = [
  { name: 'data', label: 'Data', type: 'date', required: true },
  { name: 'turno', label: 'Turno', type: 'select', required: true, options: ['Manhã', 'Tarde', 'Noite'] },
  { name: 'categoria', label: 'Categoria', type: 'text', required: true },
  { name: 'atleta', label: 'Atleta', type: 'text', required: true },
  { name: 'peso', label: 'Peso', type: 'number', required: false },
  { name: 'protocolo', label: 'Protocolo', type: 'text', required: false },
  { name: 'peitoral', label: 'Peitoral', type: 'number', required: false },
  { name: 'biciptal', label: 'Biciptal', type: 'number', required: false },
  { name: 'triciptal', label: 'Triciptal', type: 'number', required: false },
  { name: 'axilar', label: 'Axilar', type: 'number', required: false },
  { name: 'suprailiaca', label: 'Suprailiaca', type: 'number', required: false },
  { name: 'abdominal', label: 'Abdominal', type: 'number', required: false },
  { name: 'subescapular', label: 'Subescapular', type: 'number', required: false },
  { name: 'coxa', label: 'Coxa', type: 'number', required: false },
  { name: 'panturrilha', label: 'Panturrilha', type: 'number', required: false },
  { name: 'percGorduraPetroski', label: '% Gordura Petroski', type: 'number', required: false },
  { name: 'percGorduraJacksonPullock', label: '% Gordura Jackson & Pollock', type: 'number', required: false },
  { name: 'percGorduraFaulkner', label: '% Gordura Faulkner', type: 'number', required: false },
  { name: 'massaMuscular', label: 'Massa Muscular', type: 'number', required: false },
  { name: 'porcMuscular', label: '% Muscular', type: 'number', required: false },
  { name: 'massaOssea', label: 'Massa Óssea', type: 'number', required: false },
  { name: 'porcOssea', label: '% Óssea', type: 'number', required: false },
  { name: 'massaResidual', label: 'Massa Residual', type: 'number', required: false },
  { name: 'porcResidual', label: '% Residual', type: 'number', required: false },
  { name: 'massaGorda', label: 'Massa Gorda', type: 'number', required: false },
  { name: 'percGordura', label: '% Gordura', type: 'number', required: false },
  { name: 'diametroPunho', label: 'Diâmetro do Punho', type: 'number', required: false },
  { name: 'diametroFemur', label: 'Diâmetro do Fêmur', type: 'number', required: false },
  { name: 'diametroUmero', label: 'Diâmetro do Úmero', type: 'number', required: false },
  { name: 'bioimp_MassaMuscular', label: 'Bioimpedância Massa Muscular', type: 'number', required: false },
  { name: 'bioimp_PorcMuscular', label: 'Bioimpedância % Muscular', type: 'number', required: false },
  { name: 'bioimp_MassaOssea', label: 'Bioimpedância Massa Óssea', type: 'number', required: false },
  { name: 'bioimp_PorcOssea', label: 'Bioimpedância % Óssea', type: 'number', required: false },
  { name: 'bioimp_MassaGorda', label: 'Bioimpedância Massa Gorda', type: 'number', required: false },
  { name: 'bioimp_PorcGorda', label: 'Bioimpedância % Gordura', type: 'number', required: false },
  { name: 'bioimp_Agua', label: 'Bioimpedância Água', type: 'number', required: false },
  { name: 'geb', label: 'Gasto Energético Basal', type: 'number', required: false },
  { name: 'somaDobras', label: 'Soma das Dobras', type: 'number', required: false },
  { name: 'obs', label: 'Observações', type: 'textarea', required: false },
  { name: 'zAdipose', label: 'Z-Adipose', type: 'number', required: false },
  { name: 'indiceMuscularOsseo', label: 'Índice Muscular-Ósseo', type: 'number', required: false },
  { name: 'metaPeso', label: 'Meta de Peso', type: 'number', required: false },
  { name: 'metaSomaDobras', label: 'Meta Soma Dobras', type: 'number', required: false },
  { name: 'metaZAdipose', label: 'Meta Z-Adipose', type: 'number', required: false },
  { name: 'metaMassaGorda', label: 'Meta Massa Gorda', type: 'number', required: false },
  { name: 'metaMassaMuscular', label: 'Meta Massa Muscular', type: 'number', required: false },
  { name: 'metaMassaOssea', label: 'Meta Massa Óssea', type: 'number', required: false },
  { name: 'metaIndiceMuscularOsseo', label: 'Meta Índice Muscular-Ósseo', type: 'number', required: false },
  { name: 'circunferenciaBraco', label: 'Circunferência do Braço', type: 'number', required: false },
  { name: 'circunferenciaCintura', label: 'Circunferência da Cintura', type: 'number', required: false },
  { name: 'circunferenciaCoxaMedia', label: 'Circunferência da Coxa Média', type: 'number', required: false },
  { name: 'alturaSentado', label: 'Altura Sentado', type: 'number', required: false },
  { name: 'massaMagra', label: 'Massa Magra', type: 'number', required: false },
  { name: 'bioimp_MassaMagra', label: 'Bioimpedância Massa Magra', type: 'number', required: false },
  { name: 'supraespinal', label: 'Supraespinal', type: 'number', required: false },
  { name: 'circunferenciaPeitoral', label: 'Circunferência do Peitoral', type: 'number', required: false },
  { name: 'circunferenciaBracoRelaxado', label: 'Circunferência do Braço Relaxado', type: 'number', required: false },
  { name: 'circunferenciaAbdomen', label: 'Circunferência do Abdômen', type: 'number', required: false },
  { name: 'circunferenciaQuadril', label: 'Circunferência do Quadril', type: 'number', required: false },
  { name: 'circunferenciaPanturrilha', label: 'Circunferência da Panturrilha', type: 'number', required: false },
  { name: 'porcMagra', label: '% Magra', type: 'number', required: false },
  { name: 'estagioMaturacionalDM', label: 'Estágio Maturacional DM', type: 'text', required: false },
  { name: 'estagioMaturacionalDMA', label: 'Estágio Maturacional DMA', type: 'text', required: false },
  { name: 'estagioMaturacionalPHV', label: 'Estágio Maturacional PHV', type: 'text', required: false },
  { name: 'estagioMaturacionalPreditiva', label: 'Estágio Maturacional Preditiva', type: 'text', required: false },
  { name: 'estagioMaturacao', label: 'Estágio de Maturação', type: 'text', required: false },
  { name: 'diametroCotovelo', label: 'Diâmetro do Cotovelo', type: 'number', required: false },
  { name: 'diametroTornozelo', label: 'Diâmetro do Tornozelo', type: 'number', required: false },
  { name: 'circunferenciaBracoRelaxadoDireito', label: 'Circunferência Braço Relaxado Direito', type: 'number', required: false },
  { name: 'circunferenciaBracoRelaxadoEsquerdo', label: 'Circunferência Braço Relaxado Esquerdo', type: 'number', required: false },
  { name: 'circunferenciaBracoContraidoDireito', label: 'Circunferência Braço Contraído Direito', type: 'number', required: false },
  { name: 'circunferenciaBracoContraidoEsquerdo', label: 'Circunferência Braço Contraído Esquerdo', type: 'number', required: false },
  { name: 'circunferenciaCoxaDireita', label: 'Circunferência Coxa Direita', type: 'number', required: false },
  { name: 'circunferenciaCoxaEsquerda', label: 'Circunferência Coxa Esquerda', type: 'number', required: false },
  { name: 'circunferenciaPanturrilhaDireita', label: 'Circunferência Panturrilha Direita', type: 'number', required: false },
  { name: 'circunferenciaPanturrilhaEsquerda', label: 'Circunferência Panturrilha Esquerda', type: 'number', required: false },
  { name: 'envergadura', label: 'Envergadura', type: 'number', required: false },
  { name: 'comprimentoBracoDireito', label: 'Comprimento do Braço Direito', type: 'number', required: false },
  { name: 'comprimentoBracoEsquerdo', label: 'Comprimento do Braço Esquerdo', type: 'number', required: false },
  { name: 'alturaComSalto', label: 'Altura com Salto', type: 'number', required: false },
]

