export interface FormField {
  name: string
  label: string
  type: 'text' | 'number' | 'date' | 'select' | 'textarea' | 'time'
  required: boolean
  options?: string[]
}

export interface Antropometria {
  id: string
  data: string
  turno: string
  categoria: string
  atleta: string
  peso: number
  protocolo: string
  peitoral: number
  biciptal: number
  triciptal: number
  axilar: number
  suprailiaca: number
  abdominal: number
  subescapular: number
  coxa: number
  panturrilha: number
  percGorduraPetroski: number
  percGorduraJacksonPullock: number
  percGorduraFaulkner: number
  massaMuscular: number
  porcMuscular: number
  massaOssea: number
  porcOssea: number
  massaResidual: number
  porcResidual: number
  massaGorda: number
  percGordura: number
  diametroPunho: number
  diametroFemur: number
  diametroUmero: number
  bioimp_MassaMuscular: number
  bioimp_PorcMuscular: number
  bioimp_MassaOssea: number
  bioimp_PorcOssea: number
  bioimp_MassaGorda: number
  bioimp_PorcGorda: number
  bioimp_Agua: number
  geb: number
  somaDobras: number
  obs: string
  zAdipose: number
  indiceMuscularOsseo: number
  metaPeso: number
  metaSomaDobras: number
  metaZAdipose: number
  metaMassaGorda: number
  metaMassaMuscular: number
  metaMassaOssea: number
  metaIndiceMuscularOsseo: number
  circunferenciaBraco: number
  circunferenciaCintura: number
  circunferenciaCoxaMedia: number
  alturaSentado: number
  massaMagra: number
  bioimp_MassaMagra: number
  supraespinal: number
  circunferenciaPeitoral: number
  circunferenciaBracoRelaxado: number
  circunferenciaAbdomen: number
  circunferenciaQuadril: number
  circunferenciaPanturrilha: number
  porcMagra: number
  estagioMaturacionalDM: string
  estagioMaturacionalDMA: string
  estagioMaturacionalPHV: string
  estagioMaturacionalPreditiva: string
  estagioMaturacao: string
  diametroCotovelo: number
  diametroTornozelo: number
  circunferenciaBracoRelaxadoDireito: number
  circunferenciaBracoRelaxadoEsquerdo: number
  circunferenciaBracoContraidoDireito: number
  circunferenciaBracoContraidoEsquerdo: number
  circunferenciaCoxaDireita: number
  circunferenciaCoxaEsquerda: number
  circunferenciaPanturrilhaDireita: number
  circunferenciaPanturrilhaEsquerda: number
  envergadura: number
  comprimentoBracoDireito: number
  comprimentoBracoEsquerdo: number
  alturaComSalto: number
}
